var values = new Array(2);
values[0] = 10;
values[1] = 20;
values[2] = 22;
values[3] = 23;
console.log(values.toString());
var letter = new Array(3);
values[0] = 10;
values[1] = 20;
values[2] = "dhdc";
values[3] = 23;
console.log(values.toString());
